###################################################
# header_common.py
# This file contains common declarations.
# DO NOT EDIT THIS FILE!
###################################################

#menu variables
escape_menu_item_height = 40



bignum = 0x40000000000000000000000000000000

op_num_value_bits = 24 + 32

tag_register        =  1
tag_variable        =  2
tag_string          =  3
tag_item            =  4
tag_troop           =  5
tag_faction         =  6
tag_quest           =  7
tag_party_tpl       =  8
tag_party           =  9
tag_scene           = 10
tag_mission_tpl     = 11
tag_menu            = 12
tag_script          = 13
tag_particle_sys    = 14
tag_scene_prop      = 15
tag_sound           = 16
tag_local_variable  = 17
tag_map_icon        = 18
tag_skill           = 19
tag_mesh            = 20
tag_presentation    = 21
tag_quick_string    = 22
tag_track           = 23
tag_tableau         = 24
tag_animation       = 25
tags_end            = 26


opmask_register             =  tag_register       << op_num_value_bits
opmask_variable             =  tag_variable       << op_num_value_bits
##opmask_string             =  tag_string         << op_num_value_bits
##opmask_item_index         =  tag_item           << op_num_value_bits
##opmask_troop_index        =  tag_troop          << op_num_value_bits
##opmask_faction_index      =  tag_faction        << op_num_value_bits
opmask_quest_index          =  tag_quest          << op_num_value_bits
##opmask_p_template_index   =  tag_party_tpl      << op_num_value_bits
##opmask_party_index        =  tag_party          << op_num_value_bits
##opmask_scene_index        =  tag_scene          << op_num_value_bits
##opmask_mission_tpl_index  =  tag_mission_tpl    << op_num_value_bits
##opmask_menu_index         =  tag_menu           << op_num_value_bits
##opmask_script             =  tag_script         << op_num_value_bits
##opmask_particle_sys       =  tag_particle_sys   << op_num_value_bits
##opmask_scene_prop         =  tag_scene_prop     << op_num_value_bits
##opmask_sound              =  tag_sound          << op_num_value_bits
##opmask_map_icon           =  tag_map_icon       << op_num_value_bits
opmask_local_variable       =  tag_local_variable << op_num_value_bits
opmask_quick_string         =  tag_quick_string   << op_num_value_bits


def reg(reg_no):
  if (reg_no < 0):
    print ("Error register_no negative")
    cause_error()
  return opmask_register | reg_no

def find_object(objects,object_id):
  result = -1
  num_objects = len(objects)
  i_object = 0
  object_id_lowercase = object_id.lower()
  while (i_object < num_objects) and (result == -1):
    object = objects[i_object]
    if (object[0].lower() == object_id_lowercase):
      result = i_object
    i_object += 1
  return result


# LAV TWEAKS BEGIN

for index in range(128):
	globals()['s%d' % index] = index
	globals()['pos%d' % index] = index
	globals()['reg%d' % index] = opmask_register | index
	globals()['freg%d' % index] = index #fixed point registers (wse)

pos_belfry_begin = 64
# LAV TWEAKS END

spf_all_teams_are_enemy                      = 0x00000001, 
spf_is_horseman                              = 0x00000002,
spf_examine_all_spawn_points                 = 0x00000004,
spf_team_0_spawn_far_from_entry_32           = 0x00000008,
spf_team_1_spawn_far_from_entry_0            = 0x00000010,
spf_team_1_spawn_far_from_entry_66           = 0x00000020,
spf_team_0_spawn_near_entry_0                = 0x00000040,
spf_team_0_spawn_near_entry_66               = 0x00000080,
spf_team_1_spawn_near_entry_32               = 0x00000100,
spf_team_0_walkers_spawn_at_high_points      = 0x00000200,
spf_team_1_walkers_spawn_at_high_points      = 0x00000400,
spf_try_to_spawn_close_to_at_least_one_enemy = 0x00000800,
spf_care_agent_to_agent_distances_less       = 0x00001000,

#human bones
hb_abdomen = 0
hb_thigh_l = 1
hb_calf_l = 2
hb_foot_l = 3
hb_thigh_r = 4
hb_calf_r = 5
hb_foot_r = 6
hb_spine = 7
hb_thorax = 8
hb_head = 9
hb_shoulder_l = 10
hb_upperarm_l = 11
hb_forearm_l = 12
hb_hand_l = 13
hb_item_l = 14
hb_shoulder_r = 15
hb_upperarm_r = 16
hb_forearm_r = 17
hb_hand_r = 18
hb_item_r = 19

#Horse bones (from wse)
hrsb_pelvis = 0
hrsb_spine_1 = 1
hrsb_spine_2 = 2
hrsb_spine_3 = 3
hrsb_neck_1 = 4
hrsb_neck_2 = 5
hrsb_neck_3 = 6
hrsb_head = 7
hrsb_l_clavicle = 8
hrsb_l_upper_arm = 9
hrsb_l_forearm = 10
hrsb_l_hand = 11
hrsb_l_front_hoof = 12
hrsb_r_clavicle = 13
hrsb_r_upper_arm = 14
hrsb_r_forearm = 15
hrsb_r_hand = 16
hrsb_r_front_hoof = 17
hrsb_l_thigh = 18
hrsb_l_calf = 19
hrsb_l_foot = 20
hrsb_l_back_hoof = 21
hrsb_r_thigh = 22
hrsb_r_calf = 23
hrsb_r_foot = 24
hrsb_r_back_hoof = 25
hrsb_tail_1 = 26
hrsb_tail_2 = 27

#object types for "try_for_prop_instances" operation
somt_object = 1
somt_entry = 2
somt_item = 3
somt_baggage = 4
somt_flora = 5
somt_passage = 6
somt_spawned_item = 7
somt_spawned_single_ammo_item = 8
somt_spawned_unsheathed_item = 9
somt_shield = 10
somt_temporary_object = 11

#Tooltip types (wse)
tooltip_agent = 1
tooltip_horse = 2
tooltip_my_horse = 3
tooltip_container = 5
tooltip_door = 6
tooltip_item = 7
tooltip_leave_area = 8
tooltip_prop = 9
tooltip_destructible_prop = 10

#Attack directions (wse)
atk_thrust = 0
atk_right_swing = 1
atk_left_swing = 2
atk_overhead = 3

#Game windows (wse)
window_inventory = 7
window_party = 8
window_character = 11

#Inventory window modes (wse)
iwm_view        = 0
iwm_loot        = 1
iwm_trade       = 2
iwm_chest       = 3
iwm_equip_other = 4

#Party window modes (wse)
pwm_view             = 0
pwm_exchange_members = 1
pwm_trade_prisoners  = 2
pwm_buy_mercenaries  = 3
pwm_battle_result    = 4
pwm_battle_view      = 5
pwm_exchange_leader  = 6
pwm_give_members     = 7

#Character window modes (wse)
cwm_edit  = 0
cwm_view  = 1
cwm_train = 2

#Agent body meta meshes (wse)
bmm_head = 0
bmm_beard = 1
bmm_hair = 2
bmm_helmet = 3
bmm_armor = 4
bmm_trousers = 5
bmm_left_foot = 6
bmm_right_foot = 7
bmm_armature = 8
bmm_item_1 = 9
bmm_item_2 = 10
bmm_item_3 = 11
bmm_item_4 = 12
bmm_missile_1 = 13
bmm_missile_2 = 14
bmm_missile_3 = 15
bmm_missile_4 = 16
bmm_carry_1 = 17
bmm_carry_2 = 18
bmm_carry_3 = 19
bmm_carry_4 = 20
bmm_unknown_2 = 21
bmm_left_hand = 22
bmm_right_hand = 23
bmm_left_bracer = 24
bmm_right_bracer = 25
bmm_banner = 26
bmm_name = 27

#Dialog states
dlg_start = 0
dlg_party_encounter = 1
dlg_prisoner_liberated = 2
dlg_enemy_defeated = 3
dlg_party_relieved = 4
dlg_event_triggered = 5
dlg_close_window = 6
dlg_trade = 7
dlg_exchange_members = 8
dlg_trade_prisoners =9
dlg_buy_mercenaries = 10
dlg_view_char = 11
dlg_training = 12
dlg_member_chat = 13
dlg_prisoner_chat = 14

#Floating point registers (wse)
fp0 = 0
fp1 = 1
fp2 = 2
fp3 = 3
fp4 = 4
fp5 = 5
fp6 = 6
fp7 = 7
fp8 = 8
fp9 = 9
fp10 = 10
fp11 = 11
fp12 = 12
fp13 = 13
fp14 = 14
fp15 = 15
fp16 = 16
fp17 = 17
fp18 = 18
fp19 = 19
fp20 = 20
fp21 = 21
fp22 = 22
fp23 = 23
fp24 = 24
fp25 = 25
fp26 = 26
fp27 = 27
fp28 = 28
fp29 = 29
fp30 = 30
fp31 = 31
fp32 = 32
fp33 = 33
fp34 = 34
fp35 = 35
fp36 = 36
fp37 = 37
fp38 = 38
fp39 = 39
fp40 = 40
fp41 = 41
fp42 = 42
fp43 = 43
fp44 = 44
fp45 = 45
fp46 = 46
fp47 = 47
fp48 = 48
fp49 = 49
fp50 = 50
fp51 = 51
fp52 = 52
fp53 = 53
fp54 = 54
fp55 = 55
fp56 = 56
fp57 = 57
fp58 = 58
fp59 = 59
fp60 = 60
fp61 = 61
fp62 = 62
fp63 = 63
fp64 = 64
fp65 = 65
fp66 = 66
fp67 = 67
fp68 = 68
fp69 = 69
fp70 = 70
fp71 = 71
fp72 = 72
fp73 = 73
fp74 = 74
fp75 = 75
fp76 = 76
fp77 = 77
fp78 = 78
fp79 = 79
fp80 = 80
fp81 = 81
fp82 = 82
fp83 = 83
fp84 = 84
fp85 = 85
fp86 = 86
fp87 = 87
fp88 = 88
fp89 = 89
fp90 = 90
fp91 = 91
fp92 = 92
fp93 = 93
fp94 = 94
fp95 = 95
fp96 = 96
fp97 = 97
fp98 = 98
fp99 = 99
fp100 = 100
fp101 = 101
fp102 = 102
fp103 = 103
fp104 = 104
fp105 = 105
fp106 = 106
fp107 = 107
fp108 = 108
fp109 = 109
fp110 = 110
fp111 = 111
fp112 = 112
fp113 = 113
fp114 = 114
fp115 = 115
fp116 = 116
fp117 = 117
fp118 = 118
fp119 = 119
fp120 = 120
fp121 = 121
fp122 = 122
fp123 = 123
fp124 = 124
fp125 = 125
fp126 = 126
fp127 = 127

sort_f_desc = 1 #wse
sort_f_ci   = 2

sort_m_int_asc = 0 #wse
sort_m_int_desc = sort_f_desc

sort_m_str_cs_asc  = 0 #wse
sort_m_str_cs_desc = sort_f_desc
sort_m_str_ci_asc  = sort_f_ci
sort_m_str_ci_desc = sort_f_ci | sort_f_desc

LUA_TNONE         = -1 #wse
LUA_TNIL       = 0
LUA_TBOOLEAN      = 1
LUA_TLIGHTUSERDATA   = 2
LUA_TNUMBER       = 3
LUA_TSTRING       = 4
LUA_TTABLE        = 5
LUA_TFUNCTION     = 6
LUA_TUSERDATA     = 7
LUA_TTHREAD       = 8