###################################################
# header_dialogs.py
# This file contains declarations for dialogs
# DO NOT EDIT THIS FILE!
###################################################

speaker_pos = 0
ipt_token_pos = 1
sentence_conditions_pos = 2
text_pos = 3
opt_token_pos = 4
sentence_consequences_pos = 5


anyone              = 0x00000fff # Dialog option won't check for specific troop id when game jumps to its dialog state
plyr                = 0x00010000 # Game will take player agent as a speaker for this option
party_tpl           = 0x00020000 # This option will be called only when you meet a party of specified template on the global map. See Native examples for syntax
auto_proceed        = 0x00040000 # Dialog answer will instantly proceed to the next one, not showing you its text or anything. Useful for setting important variables between dialog states
multi_line          = 0x00080000 # Makes a player option jump to the next line when the amount of text exceeds a single one. Requires |plyr to work

# These create a list of player options (so plyr| is required), where each option is a separate object. The amount of options depends on the last number in respective ID_xxx.py file (max 1024).
# Should be used on pair with store_repeat_object operation (in both brackets of the dialog answer). The example is shown here: https://imgur.com/a/dizGEM9
repeat_for_factions = 0x00001000
repeat_for_parties  = 0x00002000
repeat_for_troops   = 0x00003000
repeat_for_100      = 0x00004000
repeat_for_1000     = 0x00005000


suf_other_bits   = 20

def other(other_troop_id):
  return other_troop_id << suf_other_bits
