from compiler import *
from module_items import imodbits_none, imodbits_horse_basic
from module_troops import *
from module_parties import pf_location

register_plugin(__name__)  # v0.1
dialogs = [
    [
        trp.mercenary_master,
        "start",
        [],
        "Are you, perchance, looking for some mercenaries?",
        "merc_master_talk",
        [],
    ],
    [
        trp.tournament_master,
        "start",
        [],
        "Sorry, the arena is closed at the moment. But some guy at the tavern organizes fistfights in the cellar. You might want to ask around there.",
        "close_window",
        [],
    ],
    [
        trp.zendar_merchant,
        "start",
        [],
        "You need quick money? I buy anything, no questions asked.",
        "npc_merchant_talk",
        [],
    ],
    [
        trp.constable_hareck,
        "start",
        [(troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 0)],
        "Welcome to Zendar, young {man/lady}. Don't start any trouble.",
        "hareck_introduce_1",
        [],
    ],
    [
        trp.constable_hareck,
        "start",
        [],
        "Hello again, {playername}.",
        "constable_talk",
        [],
    ],
    [
        trp.zendar_bodger,
        "start",
        [(troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 0)],
        "Greetings, {sir/madam}! Welcome to the Calradian Polearm Emporium!",
        "bodger_introduce_1",
        [],
    ],
    [
        trp.zendar_bodger,
        "start",
        [],
        "Greetings, {playername}! Welcome to the Calradian Polearm Emporium!",
        "bodger_talk",
        [],
    ],
    [trp.xerina, "start", [], "Hey, {cutie/sis}!", "champions_talk", []],
    [trp.dranton, "start", [], "Greetings, traveller!", "champions_talk", []],
    [trp.kradus, "start", [], "Hello, {boy/girl}!", "champions_talk", []],
    [
        anyone,
        "start",
        [(eq, "$fistfight_opponent", "$g_talk_troop")],
        "What's up, rookie? Getting cold feet?",
        "champions_back_down",
        [],
    ],
    [
        trp.fight_promoter,
        "start",
        [(eq, "$fistfight_warnings", 1)],
        "Hey, no kicking! Last warning.",
        "close_window",
        [],
    ],
    [
        trp.fight_promoter,
        "start",
        [(eq, "$fistfight_warnings", 2)],
        "No kicking! You're disqualified.",
        "close_window",
        [
            (assign, "$fistfight_warnings", 0),
            (assign, "$fistfight_result", -3),
            (finish_mission),
        ],
    ],
    [
        trp.fight_promoter,
        "start",
        [(troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 0)],
        "You look like a {fellow/lady} who can take a few hard knocks -- and deal them out, too. I have a business proposition for you.",
        "fistfight_response",
        [],
    ],
    [
        trp.fight_promoter,
        "start",
        [(eq, "$fistfight_result", -3)],
        "Hey, you don't need to resort to dirty tricks to win. Besides, fouls play always lead to disputes about the bets, so please knock it off next time.",
        "close_window",
        [(assign, "$fistfight_result", 0)],
    ],
    [
        trp.fight_promoter,
        "start",
        [(eq, "$fistfight_result", -2)],
        "You quit? I am a bit disappointed. Remember, the matches that seem to go worst tend to pay best.",
        "close_window",
        [(assign, "$fistfight_result", 0)],
    ],
    [
        trp.fight_promoter,
        "start",
        [(eq, "$fistfight_result", -1), (lt, "$fistfight_points_opponent", 5)],
        "Ouch, that must have hurt. Are you ready to fight again?",
        "fistfight_response_confirm",
        [(assign, "$fistfight_result", 0)],
    ],
    [
        trp.fight_promoter,
        "start",
        [(eq, "$fistfight_result", -1)],
        "Well, that certainly wasn't your best fight. Want a rematch?",
        "fistfight_response_confirm",
        [(assign, "$fistfight_result", 0)],
    ],
    [
        trp.fight_promoter,
        "start",
        [(eq, "$fistfight_result", 1), (le, "$fistfight_bets", -10)],
        "Didn't you listen to me? I will explain it again, as simple as possible. You winning the fight doesn't get us money. People betting on the loser gets us money.\
 You must be behind on points as long as possible, so people bet on your opponent. Only then can you start to score hits and win. You won the fight, but we lost big time on the bets.",
        "close_window",
        [(assign, "$fistfight_result", 0)],
    ],
    [
        trp.fight_promoter,
        "start",
        [(eq, "$fistfight_result", 1), (le, "$fistfight_bets", 0)],
        "That was a close fight down there. You won, but we lost a few denars on the bets. Try to let your opponent get a bit more lead next time, or maybe challenge someone with a reputation as a good fighter.",
        "close_window",
        [(assign, "$fistfight_result", 0)],
    ],
    [
        trp.fight_promoter,
        "start",
        [(eq, "$fistfight_result", 1), (assign, reg1, "$fistfight_bets")],
        "Good job! We came out ahead on the bets. Here's your share - {reg1} denars.",
        "fistfight_response_won",
        [
            (troop_add_gold, "trp_player", "$fistfight_bets"),
            (assign, "$fistfight_result", 0),
        ],
    ],
    [
        trp.fight_promoter,
        "start",
        [],
        "Hello again, {fellow/lady}! Care for another round?",
        "fistfight_response_confirm",
        [],
    ],
    [
        anyone | plyr,
        "fistfight_response",
        [],
        "How's that?",
        "fistfight_response_2",
        [(troop_set_slot, "$g_talk_troop", slot_troop_met_previously, 1)],
    ],
    [
        anyone,
        "fistfight_response_2",
        [],
        "Good -- I'm glad you're interested. Here's the plan... It's a little complicated, so listen well. ",
        "fistfight_response_2a",
        [],
    ],
    [
        anyone,
        "fistfight_response_2a",
        [],
        "You and some other fellow will start up a fight. No weapons, no armor -- I'll sit back and take bets, and split the profits with the winner. If we make a loss, then I'll cover it. You've got nothing to lose -- except a bit of blood, of course.",
        "fistfight_response_3",
        [],
    ],
    [
        anyone,
        "fistfight_response_3",
        [],
        "However, we can't organize this like one of those nice arena bouts, where everyone places their bets beforehand. People will walk in, drawn by the noise, and put a denar or two on whichever one of your two they think is winning. I'll give 'em even odds -- anything else is going to be too tricky for someone who's already on his third flagon of ale.",
        "fistfight_response_3a",
        [],
    ],
    [
        anyone,
        "fistfight_response_3a",
        [],
        "We'll keep the rules simple. Winner is the first to land five solid punches, or knock the other fighter out. And try to keep it at least somewhat clean. No kicking, no biting, no scratching. And please don't grapple. It's a mess to score properly, and leads to endless disputes about the bets.",
        "fistfight_response_4",
        [],
    ],
    [
        anyone,
        "fistfight_response_4",
        [],
        "So, as you can see, the trick is to take a few hits so it looks like you're losing, and people bet against you -- and then come back fast, and win, before the betting can turn. The best way to make money is for you to be battered almost to the floor, and then jump back off your feet and take the other guy down. However, you have to win in the end, to actually get the money.",
        "fistfight_response_4a",
        [],
    ],
    [
        anyone,
        "fistfight_response_4a",
        [],
        "Also, you can't stretch the fight out too long, or people will suspect a fix. So, one of you has to take a punch every so often. I don't care whose blood is spilled, but there has to be some blood.",
        "fistfight_response_5",
        [],
    ],
    [
        anyone,
        "fistfight_response_5",
        [],
        "And one other thing -- most of the fighters around here don't take too well to complexity. They're just going to come straight at you. It's up to you to supply the artistry.",
        "fistfight_response_5a",
        [],
    ],
    [
        anyone,
        "fistfight_response_5a",
        [],
        "So, what do you think?",
        "fistfight_response_confirm",
        [],
    ],
    [
        anyone,
        "fistfight_response_won",
        [],
        "Want to go for another round?",
        "fistfight_response_confirm",
        [],
    ],
    [
        anyone | plyr,
        "fistfight_response_confirm",
        [],
        "Sure, sounds like fun.",
        "close_window",
        [
          (call_script, "script_start_fistfight")
        ],
    ],
    [
        anyone | plyr,
        "fistfight_response_confirm",
        [],
        "I have better things to do",
        "close_window",
        [],
    ],
     [
        anyone | plyr,
        "bodger_introduce_1",
        [],
        "Thank you, my good man.",
        "bodger_introduce_2",
        [(troop_set_slot, "$g_talk_troop", slot_troop_met_previously, 1)],
    ],
    [
        anyone | plyr,
        "bodger_introduce_1",
        [],
        "Sorry, I don't have time for this.",
        "close_window",
        [(troop_set_slot, "$g_talk_troop", slot_troop_met_previously, 1)],
    ],
    [
        anyone,
        "bodger_introduce_2",
        [],
        "What can I do for you, {sir/madam}?",
        "bodger_introduce_3",
        [],
    ],
    [
        anyone | plyr,
        "bodger_introduce_3",
        [],
        "I was, uh, leisurely strolling through the countryside, ruminating about this and that, when I noticed I was feeling a bit enervated.",
        "bodger_introduce_4",
        [],
    ],
    [
        anyone,
        "bodger_introduce_4",
        [],
        "Enervated, {sir/madam}?",
        "bodger_introduce_5",
        [],
    ],
    [anyone | plyr, "bodger_introduce_5", [], "Etiolated.", "bodger_introduce_6", []],
    [anyone, "bodger_introduce_6", [], "Eh?", "bodger_introduce_7", []],
    [
        anyone | plyr,
        "bodger_introduce_7",
        [],
        "No good for fighting.",
        "bodger_introduce_8",
        [],
    ],
    [
        anyone,
        "bodger_introduce_8",
        [],
        "Ah, you want weapons?",
        "bodger_introduce_9",
        [],
    ],
    [
        anyone | plyr,
        "bodger_introduce_9",
        [],
        "In a nutshell. And I thought to myself, 'a long, cylindrical wooden object menacing with spiky protrusions of a ferric material would do the trick',\
 so, I curtailed my ruminating activites, sallied forth, and infiltrated your place of purveyance to negotiate the vending of some martial contrievances!",
        "bodger_introduce_10",
        [],
    ],
    [anyone, "bodger_introduce_10", [], "Come again?", "bodger_introduce_11", []],
    [
        anyone | plyr,
        "bodger_introduce_11",
        [],
        "I want to buy a polearm.",
        "bodger_introduce_12",
        [],
    ],
    [
        anyone,
        "bodger_introduce_12",
        [],
        "Oh, I thought you were complaining about the poor lighting.",
        "bodger_introduce_13",
        [],
    ],
    [
        anyone | plyr,
        "bodger_introduce_13",
        [],
        "Oh, heaven forbid: I am one who delights in a bit of a gloomy atmosphere!",
        "bodger_introduce_14",
        [],
    ],
    [anyone, "bodger_introduce_14", [], "Sorry?", "bodger_introduce_15", []],
    [
        anyone | plyr,
        "bodger_introduce_15",
        [],
        "I like it dark.",
        "bodger_introduce_16",
        [],
    ],
    [
        anyone,
        "bodger_introduce_16",
        [],
        "So no need to light another lamp?",
        "bodger_introduce_17",
        [],
    ],
    [
        anyone | plyr,
        "bodger_introduce_17",
        [],
        "Most certainly not! Now then, a polearm please, my good man.",
        "bodger_introduce_18",
        [],
    ],
    [
        anyone,
        "bodger_introduce_18",
        [],
        "Certainly, {sir/madam}. What would you like?",
        "bodger_polearm_choice",
        [
            (try_for_range, ":slot", "itm_bardiche", "itm_wooden_shield"),
              (troop_set_slot, "trp_temp_troop", ":slot", 0),
            (try_end),
        ],
    ],
    [anyone, "bodger_ask_no", [], "No.", "bodger_polearm_choice", []],
    [anyone, "bodger_prechoice", [], "What then?", "bodger_polearm_choice", []],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_battle_fork", 0)],
        "This Battle Fork please, stout yeoman.",
        "bodger_ask_battle_fork",
        [(troop_set_slot, "trp_temp_troop", "itm_battle_fork", 1)],
    ],
    [
        anyone,
        "bodger_ask_battle_fork",
        [],
        "{Sir/Madam}, that's a Military Fork.",
        "bodger_ask_battle_fork_2",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_battle_fork_2",
        [],
        "My apologies. Then I'd like that Military Fork.",
        "bodger_ask_battle_fork_3",
        [],
    ],
    [
        anyone,
        "bodger_ask_battle_fork_3",
        [],
        "It's for display only. Wouldn't hold up in a fight.",
        "bodger_polearm_choice",
        [],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_bec_de_corbin_a", 0)],
        "A Footman's Hammer, maybe?",
        "bodger_ask_bec_de_corbin",
        [(troop_set_slot, "trp_temp_troop", "itm_bec_de_corbin_a", 1)],
    ],
    [
        anyone,
        "bodger_ask_bec_de_corbin",
        [],
        "I was expecting a new shipment this morning, {sir/madam}.",
        "bodger_polearm_choice",
        [],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_glaive", 0)],
        "I'd like the Glaive over there.",
        "bodger_ask_glaive",
        [(troop_set_slot, "trp_temp_troop", "itm_glaive", 1)],
    ],
    [
        anyone,
        "bodger_ask_glaive",
        [],
        "Sorry, can't sell you that one.",
        "bodger_ask_glaive_2",
        [],
    ],
    [anyone | plyr, "bodger_ask_glaive_2", [], "Why not?", "bodger_ask_glaive_3", []],
    [
        anyone,
        "bodger_ask_glaive_3",
        [],
        "It's been preordered by Brutus the Dismemberer. You don't want to annoy Brutus the Dismemberer, trust me, {sir/madam}.",
        "bodger_polearm_choice",
        [],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_hafted_blade_a", 0)],
        "One of those Hafted Blades, please.",
        "bodger_ask_hafted_blade",
        [(troop_set_slot, "trp_temp_troop", "itm_hafted_blade_a", 1)],
    ],
    [
        anyone,
        "bodger_ask_hafted_blade",
        [],
        "I'm afraid, they are evidence in an investigation against a gang of Steppe Bandits.",
        "bodger_ask_hafted_blade_2",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_hafted_blade_2",
        [],
        "And why are they here, and not at the Town Watch?",
        "bodger_ask_hafted_blade_3",
        [],
    ],
    [
        anyone,
        "bodger_ask_hafted_blade_3",
        [],
        "Constable Hareck asked me for my expertise. But once the investigation is closed, they will be auctioned off.",
        "bodger_ask_hafted_blade_4",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_hafted_blade_4",
        [],
        "When will that be?",
        "bodger_ask_hafted_blade_5",
        [],
    ],
    [
        anyone,
        "bodger_ask_hafted_blade_5",
        [],
        "Oh, very soon. Probably in no more than two or three years.",
        "bodger_polearm_choice",
        [],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_lance", 0)],
        "I'd like a Lance, please.",
        "bodger_ask_lance",
        [],
    ],
    [
        anyone,
        "bodger_ask_lance",
        [],
        "Of course, {sir/madam}. Single- or Double-Sided?",
        "bodger_ask_what_lance",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_what_lance",
        [(troop_slot_eq, "trp_temp_troop", "itm_lance", 0)],
        "A regular one, sir.",
        "bodger_ask_lance_2",
        [(troop_set_slot, "trp_temp_troop", "itm_lance", 1)],
    ],
    [
        anyone | plyr,
        "bodger_ask_what_lance",
        [(troop_slot_eq, "trp_temp_troop", "itm_double_sided_lance", 0)],
        "Double-Sided.",
        "bodger_ask_dbl_lance",
        [(troop_set_slot, "trp_temp_troop", "itm_double_sided_lance", 1)],
    ],
    [
        anyone,
        "bodger_ask_dbl_lance",
        [],
        "Wait a minute, I'll check...",
        "bodger_ask_dbl_lance_2",
        [],
    ],
    [anyone, "bodger_ask_dbl_lance_2", [], "Sorry, no.", "bodger_ask_dbl_lance_3", []],
    [
        anyone | plyr,
        "bodger_ask_dbl_lance_3",
        [(troop_slot_eq, "trp_temp_troop", "itm_lance", 0)],
        "Sigh. And a regular one?",
        "bodger_ask_lance_2",
        [(troop_set_slot, "trp_temp_troop", "itm_lance", 1)],
    ],
    [
        anyone,
        "bodger_ask_lance_2",
        [],
        "Ah, I have a Lance. Yes, {sir/madam}!",
        "bodger_ask_lance_3",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_lance_3",
        [],
        "You do! Excellent.",
        "bodger_ask_lance_4",
        [],
    ],
    [
        anyone,
        "bodger_ask_lance_4",
        [],
        "Yes, {sir/madam}. It's ah... it's a bit heavy.",
        "bodger_ask_lance_5",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_lance_5",
        [],
        "Oh, I like them heavy.",
        "bodger_ask_lance_6",
        [],
    ],
    [
        anyone,
        "bodger_ask_lance_6",
        [],
        "Well... It's very heavy, actually, {sir/madam}.",
        "bodger_ask_lance_7",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_lance_7",
        [],
        "No matter. Fetch hither the mighty polearm of the noble chevalier!",
        "bodger_ask_lance_8",
        [],
    ],
    [
        anyone,
        "bodger_ask_lance_8",
        [],
        "I...think it's a bit heavier than you'll like it, {sir/madam}.",
        "bodger_ask_lance_9",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_lance_9",
        [],
        "I don't care if it's heavier than an ancient oak tree. Hand it over, will you?",
        "bodger_ask_lance_10",
        [],
    ],
    [anyone, "bodger_ask_lance_10", [], "Oooooh no!", "bodger_ask_lance_11", []],
    [anyone | plyr, "bodger_ask_lance_11", [], "What now?", "bodger_ask_lance_12", []],
    [anyone, "bodger_ask_lance_12", [], "Termites ate it.", "bodger_ask_lance_13", []],
    [
        anyone | plyr,
        "bodger_ask_lance_13",
        [],
        "Oh, did they?",
        "bodger_ask_lance_14",
        [],
    ],
    [
        anyone,
        "bodger_ask_lance_14",
        [],
        "Yes, {sir/madam}. Quite the problem round here, {sir/madam}.",
        "bodger_polearm_choice",
        [],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (troop_slot_eq, "trp_temp_troop", "itm_glaive", 1),
            (troop_slot_eq, "trp_temp_troop", "itm_bardiche", 0),
        ],
        "Bardiche?",
        "bodger_ask_no",
        [(troop_set_slot, "trp_temp_troop", "itm_bardiche", 1)],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (troop_slot_eq, "trp_temp_troop", "itm_bardiche", 1),
            (troop_slot_eq, "trp_temp_troop", "itm_great_bardiche", 0),
        ],
        "Great Bardiche?",
        "bodger_ask_no",
        [(troop_set_slot, "trp_temp_troop", "itm_great_bardiche", 1)],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (troop_slot_eq, "trp_temp_troop", "itm_great_bardiche", 1),
            (troop_slot_eq, "trp_temp_troop", "itm_long_bardiche", 0),
        ],
        "Long Bardiche?",
        "bodger_ask_no",
        [(troop_set_slot, "trp_temp_troop", "itm_long_bardiche", 1)],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (troop_slot_eq, "trp_temp_troop", "itm_long_bardiche", 1),
            (troop_slot_eq, "trp_temp_troop", "itm_great_long_bardiche", 0),
        ],
        "Great Long Bardiche?",
        "bodger_wrong_sketch",
        [(troop_set_slot, "trp_temp_troop", "itm_great_long_bardiche", 1)],
    ],
    [
        anyone,
        "bodger_wrong_sketch",
        [],
        "I think you're drifting into another sketch, {sir/madam}.",
        "bodger_polearm_choice",
        [],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_long_hafted_knobbed_mace", 0)],
        "A Long Hafted Knobbed Mace.",
        "bodger_ask_mace_1",
        [(troop_set_slot, "trp_temp_troop", "itm_long_hafted_knobbed_mace", 1)],
    ],
    [
        anyone,
        "bodger_ask_mace_1",
        [],
        "Sorry, I was expecting a new shipment of Knobs yesterday.",
        "bodger_ask_mace_2",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_mace_2",
        [],
        "And how about a Long Hafted Spiked Mace?",
        "bodger_ask_mace_3",
        [],
    ],
    [
        anyone,
        "bodger_ask_mace_3",
        [],
        "It seems I'm completely out of maces, sorry.",
        "bodger_ask_mace_4",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_mace_4",
        [],
        "Or maybe a Long Spiked Club?",
        "bodger_ask_mace_5",
        [],
    ],
    [
        anyone,
        "bodger_ask_mace_5",
        [],
        "I do not keep such crude implements in stock, {sir/madam}. I am a civilized person, not some kind of savage.",
        "bodger_ask_mace_6",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_mace_6",
        [],
        "Or a Spiked Staff?",
        "bodger_ask_mace_7",
        [],
    ],
    [
        anyone,
        "bodger_ask_mace_7",
        [],
        "That's not even a polearm. Every child knows those are Two-handed/One-handed weapons.",
        "bodger_polearm_choice",
        [],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_military_scythe", 0)],
        "Military Scythe?",
        "bodger_ask_no",
        [(troop_set_slot, "trp_temp_troop", "itm_military_scythe", 1)],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_pike", 0)],
        "Do you have a Pike?",
        "bodger_ask_pike",
        [(troop_set_slot, "trp_temp_troop", "itm_pike", 1)],
    ],
    [
        anyone,
        "bodger_ask_pike",
        [],
        "No {sir/madam}. Why don't you ask about Awlpikes, instead?",
        "bodger_ask_pike_2",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_pike_2",
        [],
        "Would it be worth it?",
        "bodger_ask_pike_3",
        [],
    ],
    [anyone, "bodger_ask_pike_3", [], "Mmmmaybe.", "bodger_ask_pike_4", []],
    [anyone | plyr, "bodger_ask_pike_4", [], "Fine. Awlpike?", "bodger_ask_pike_5", []],
    [anyone, "bodger_ask_pike_5", [], "Nope.", "bodger_polearm_choice", []],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 2),
            (troop_slot_eq, "trp_temp_troop", "itm_poleaxe", 0),
        ],
        "Poleaxe?",
        "bodger_ask_no",
        [(troop_set_slot, "trp_temp_troop", "itm_poleaxe", 1)],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 2),
            (troop_slot_eq, "trp_temp_troop", "itm_polehammer", 0),
        ],
        "Polehammer?",
        "bodger_ask_no",
        [(troop_set_slot, "trp_temp_troop", "itm_polehammer", 1)],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 2),
            (troop_slot_eq, "trp_temp_troop", "itm_quarter_staff", 0),
        ],
        "Perchance a Quarter Staff?",
        "bodger_ask_no",
        [(troop_set_slot, "trp_temp_troop", "itm_quarter_staff", 1)],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_spear", 0)],
        "I'd like a Spear, please.",
        "bodger_ask_spears",
        [],
    ],
    [
        anyone,
        "bodger_ask_spears",
        [],
        "Certainly. What kind of spear?",
        "bodger_ask_what_spear",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_what_spear",
        [(troop_slot_eq, "trp_temp_troop", "itm_spear", 0)],
        "Oh, a regular one will do.",
        "bodger_ask_spear",
        [(troop_set_slot, "trp_temp_troop", "itm_spear", 1)],
    ],
    [
        anyone,
        "bodger_ask_spear",
        [],
        "We don't have much call for spears.",
        "bodger_ask_spear_2",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_spear_2",
        [],
        "Not much call for -- wait. A spear is the single most common polearm around.",
        "bodger_ask_spear_3",
        [],
    ],
    [
        anyone,
        "bodger_ask_spear_3",
        [],
        "Not around here, {sir/madam}.",
        "bodger_ask_spear_4",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_spear_4",
        [],
        "Oh. And what is the most common polearm around here?",
        "bodger_ask_spear_5",
        [],
    ],
    [
        anyone,
        "bodger_ask_spear_5",
        [],
        "Polehammers, {sir/madam}.",
        "bodger_ask_spear_6",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_spear_6",
        [(troop_slot_eq, "trp_temp_troop", "itm_polehammer", 0)],
        "Good. Then I'll have one of those.",
        "bodger_ask_spear_7",
        [(troop_set_slot, "trp_temp_troop", "itm_polehammer", 1)],
    ],
    [
        anyone | plyr,
        "bodger_ask_spear_6",
        [],
        "Never mind, then.",
        "bodger_ask_what_spear",
        [],
    ],
    [anyone, "bodger_ask_spear_7", [], "Sorry, fresh out.", "bodger_ask_spear_8", []],
    [
        anyone | plyr,
        "bodger_ask_spear_8",
        [],
        "Silly me. I should have known better by now.",
        "bodger_ask_what_spear",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_what_spear",
        [(troop_slot_eq, "trp_temp_troop", "itm_shortened_spear", 0)],
        "Actually, I prefer shorter spears.",
        "bodger_ask_short_spear",
        [(troop_set_slot, "trp_temp_troop", "itm_shortened_spear", 1)],
    ],
    [
        anyone,
        "bodger_ask_short_spear",
        [],
        "I never have those in stock. But for a small fee you can have a regular one cut down to your preferred length.",
        "bodger_ask_short_spear_2",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_short_spear_2",
        [],
        "Really?",
        "bodger_ask_short_spear_3",
        [],
    ],
    [anyone, "bodger_ask_short_spear_3", [], "No.", "bodger_ask_what_spear", []],
    [
        anyone | plyr,
        "bodger_ask_what_spear",
        [(troop_slot_eq, "trp_temp_troop", "itm_boar_spear", 0)],
        "A wide-bladed Boar Spear, please.",
        "bodger_ask_boar_spear",
        [(troop_set_slot, "trp_temp_troop", "itm_boar_spear", 1)],
    ],
    [
        anyone,
        "bodger_ask_boar_spear",
        [],
        "I think I sold my last one yesterday.",
        "bodger_ask_what_spear",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_what_spear",
        [(troop_slot_eq, "trp_temp_troop", "itm_bamboo_spear", 0)],
        "A nimble Bamboo Spear, perhaps?",
        "bodger_ask_bamboo_spear",
        [(troop_set_slot, "trp_temp_troop", "itm_bamboo_spear", 1)],
    ],
    [
        anyone,
        "bodger_ask_bamboo_spear",
        [],
        "But {sir/madam}? We never have those at this time of the year!",
        "bodger_ask_what_spear",
        [],
    ],
    [
        anyone | plyr,
        "bodger_ask_what_spear",
        [(troop_slot_eq, "trp_temp_troop", "itm_war_spear", 0)],
        "Maybe a sturdy War Spear?",
        "bodger_ask_war_spear",
        [(troop_set_slot, "trp_temp_troop", "itm_war_spear", 1)],
    ],
    [anyone, "bodger_ask_war_spear", [], "Sorry, no.", "bodger_ask_what_spear", []],
    [
        anyone | plyr,
        "bodger_ask_what_spear",
        [],
        "Maybe I don't need a spear, after all...",
        "bodger_prechoice",
        [],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "trp_temp_troop", "itm_staff", 0)],
        "Would you sell me simple Staff?",
        "bodger_ask_staff",
        [(troop_set_slot, "trp_temp_troop", "itm_staff", 1)],
    ],
    [
        anyone,
        "bodger_ask_staff",
        [],
        "Sorry, used them all up.",
        "bodger_polearm_choice",
        [],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 2),
            (troop_slot_eq, "trp_temp_troop", "itm_trident", 0),
        ],
        "Trident?",
        "bodger_ask_no",
        [(troop_set_slot, "trp_temp_troop", "itm_trident", 1)],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 2),
            (troop_slot_eq, "trp_temp_troop", "itm_long_voulge", 0),
        ],
        "Voulge?",
        "bodger_ask_no",
        [(troop_set_slot, "trp_temp_troop", "itm_long_voulge", 1)],
    ],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [
            (this_or_next | troop_slot_eq, "trp_temp_troop", "itm_battle_fork", 1),
            (this_or_next | troop_slot_eq, "trp_temp_troop", "itm_glaive", 1),
            (troop_slot_eq, "trp_temp_troop", "itm_hafted_blade_a", 1),
            (troop_slot_eq, "trp_temp_troop", "itm_lance", 1),
            (troop_slot_eq, "trp_temp_troop", "itm_spear", 1),
            (troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 1),
        ],
        "You... do have some polearms, don't you?",
        "bodger_confirm_a1",
        [(troop_set_slot, "$g_talk_troop", slot_troop_met_previously, 2)],
    ],
    [
        anyone,
        "bodger_confirm_a1",
        [],
        "Of course, {sir/madam}. This is a polearm shop. We have...",
        "bodger_confirm_a2",
        [],
    ],
    [
        anyone | plyr,
        "bodger_confirm_a2",
        [],
        "No no... don't tell me. I'm keen to guess.",
        "bodger_confirm_a3",
        [],
    ],
    [anyone, "bodger_confirm_a3", [], "Fair enough.", "bodger_polearm_choice", []],
    [
        anyone | plyr,
        "bodger_polearm_choice",
        [(troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 2)],
        "Do you, in fact, sell any polearms here at all?",
        "bodger_confirm_b1",
        [(troop_set_slot, "$g_talk_troop", slot_troop_met_previously, 3)],
    ],
    [anyone, "bodger_confirm_b1", [], "Yes, {sir/madam}.", "bodger_confirm_b2", []],
    [anyone | plyr, "bodger_confirm_b2", [], "Really?", "bodger_confirm_b3", []],
    [
        anyone,
        "bodger_confirm_b3",
        [],
        "No, not really, {sir/madam}.",
        "bodger_confirm_b4",
        [],
    ],
    [anyone | plyr, "bodger_confirm_b4", [], "You don't.", "bodger_confirm_b5", []],
    [
        anyone,
        "bodger_confirm_b5",
        [],
        "No, {sir/madam}. Not a single one. I was deliberately wasting your time, {sir/madam}.",
        "bodger_confirm_b6",
        [],
    ],
    [anyone | plyr, "bodger_confirm_b6", [], ". . .", "bodger_confirm_b7", []],
    [
        anyone,
        "bodger_confirm_b7",
        [],
        "Sorry, I've been pulling your leg. Please don't shoot me. What do you need?",
        "bodger_talk",
        [],
    ],
    [anyone, "bodger_pretalk", [], "Anything else?", "bodger_talk", []],
    [
        anyone | plyr,
        "bodger_talk",
        [],
        "Please show me your polearms.",
        "bodger_trade",
        [],
    ],
    [
        anyone,
        "bodger_trade",
        [],
        "Here, that's what I have right now.",
        "bodger_pretalk",
        [[change_screen_trade]],
    ],
    [anyone | plyr, "bodger_talk", [], "Goodbye.", "close_window", []],
    [
        anyone | plyr,
        "hareck_introduce_1",
        [],
        "What kind of trouble do you have in mind?",
        "hareck_introduce_2",
        [
            (troop_set_slot, "$g_talk_troop", slot_troop_met_previously, 1),
        ],
    ],
    [
        anyone | plyr,
        "hareck_introduce_1",
        [],
        "Of course not, sir.",
        "close_window",
        [],
    ],
    [
        anyone,
        "hareck_introduce_2",
        [],
        "Oh, you're of the funny sort. Well, be advised that this town is a haven for bounty hunters, mercenaries and\
 other rough folk, and your quick tongue might easily get you in a fight with someone way out of your league, if they had a bad day.",
        "hareck_introduce_3",
        [],
    ],
    [
        anyone | plyr,
        "hareck_introduce_3",
        [],
        "Thanks for the hint, I'll be careful. Who are you, by the way?",
        "hareck_introduce_4",
        [],
    ],
    [
        anyone,
        "hareck_introduce_4",
        [],
        "I'm Constable Hareck, and I'm the guy who runs this place and keeps all these soldiers of fortune in line.",
        "hareck_introduce_5",
        [],
    ],
    [
        anyone | plyr,
        "hareck_introduce_5",
        [],
        "{playername}, pleased to meet you. I haven't noticed any banner around here.\
 How come this town does not belong to one of the kingdoms?",
        "hareck_introduce_6",
        [],
    ],
    [
        anyone,
        "hareck_introduce_6",
        [],
        "First of all, Zendar has pretty formdable defenses for such a small town, and every other guy\
 you meet here is a veteran of dozens of battles, and most are highly motivated to keep Zendar independent. So an attack would be very costly.\
 On the other hand, we are a small town, don't have much industry and don't control important trade routes. There would be nothing to gain.\
 And finally, every king will eventually need the help of mercenaries. Getting on their bad side just wouldn't do.",
        "hareck_introduce_7",
        [],
    ],
    [
        anyone | plyr,
        "hareck_introduce_7",
        [],
        "How do you even pay for the cost of keeping this place?",
        "hareck_introduce_8",
        [],
    ],
    [
        anyone,
        "hareck_introduce_8",
        [],
        "It costs less than you might think, since we don't need to pay for a town watch or a standing army. As long as\
 the laws here are at the bare minimum to keep the peace, most mercenaries will happily help to enforce them. I'm only needed to settle disputes.\
 Being a neutral party also allows us to broker ransoms for prisoners of war and bounties for wanted outlaws, which can be rather profitable at times.\
 Besides, you'd be surprised how much money the tavern here makes...",
        "constable_talk",
        [],
    ],
    [
        anyone | plyr,
        "champions_talk",
        [(troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 0)],
        "Excuse me, have I seen you before?",
        "xerina_introduce",
        [],
    ],
    [
        anyone,
        "xerina_introduce",
        [(eq, "$g_talk_troop", "trp_xerina")],
        "Probably, if you have watched any tournament. Name's Xerina, by the way.",
        "dranton_introduce",
        [(troop_set_slot, "trp_xerina", slot_troop_met_previously, 1)],
    ],
    [
        anyone | other(trp.xerina),
        "xerina_introduce",
        [],
        "Probably, if you have watched any tournament. Name's Xerina, by the way.",
        "dranton_introduce",
        [(troop_set_slot, "trp_xerina", slot_troop_met_previously, 1)],
    ],
    [
        anyone,
        "dranton_introduce",
        [(eq, "$g_talk_troop", "trp_dranton")],
        "And I'm Dranton. We three travel all around Calradia, fighting in any tournament we can find.",
        "kradus_introduce",
        [(troop_set_slot, "trp_dranton", slot_troop_met_previously, 1)],
    ],
    [
        anyone | other(trp.dranton),
        "dranton_introduce",
        [],
        "And I'm Dranton. We three travel all around Calradia, fighting in any tournament we can find.",
        "kradus_introduce",
        [(troop_set_slot, "trp_dranton", slot_troop_met_previously, 1)],
    ],
    [
        anyone,
        "kradus_introduce",
        [(eq, "$g_talk_troop", "trp_kradus")],
        "And winning a decent part of them, too. I am known as Kradus.",
        "champions_introduce_1",
        [(troop_set_slot, "trp_kradus", slot_troop_met_previously, 1)],
    ],
    [
        anyone | other(trp.kradus),
        "kradus_introduce",
        [],
        "And winning a decent part of them, too. I am known as Kradus.",
        "champions_introduce_1",
        [(troop_set_slot, "trp_kradus", slot_troop_met_previously, 1)],
    ],
    [
        anyone | plyr,
        "champions_introduce_1",
        [],
        "It's a honor to meet you three. I'm {playername}.",
        "champions_introduce_2",
        [],
    ],
    [
        anyone,
        "champions_introduce_2",
        [],
        "You look like the kind of {guy/gal} who not only watches, but also fights in tournaments, right?",
        "champions_introduce_3",
        [],
    ],
    [
        anyone | plyr,
        "champions_introduce_3",
        [],
        "Yes, it's great fun!",
        "champions_introduce_4",
        [],
    ],
    [
        anyone | plyr,
        "champions_introduce_3",
        [],
        "I prefer real fights.",
        "champions_introduce_4",
        [],
    ],
    [
        anyone | plyr,
        "champions_introduce_3",
        [],
        "Actually, I detest violence.",
        "champions_introduce_4",
        [],
    ],
    [
        anyone,
        "champions_introduce_4",
        [],
        "Anyway, it was a pleasure to talk. But we have to prepare for an upcoming match. See you later!",
        "close_window",
        [],
    ],
    [
        anyone | plyr,
        "champions_talk",
        [(troop_slot_ge, "$g_talk_troop", slot_troop_met_previously, 1)],
        "I wanted to ask you something.",
        "champions_preask",
        [],
    ],
    [anyone, "champions_preask", [], "Yes?", "champions_ask", []],
    [
        anyone | plyr,
        "champions_ask",
        [],
        "Does fighting in tournaments pay well?",
        "champions_ask_money",
        [],
    ],
    [
        anyone,
        "champions_ask_money",
        [],
        "From the prices alone, you can get along quite well, but you won't get rich.\
 The real money is in betting on the outcomes. But most bookmakers aren't stupid enough to let you bet on someone else\
 if you're participating, so you'd actually have to be quite confident to win. And once you become well known in a town,\
 more people will bet on you, which will lower the amount you can gain. So it's important to travel around a lot.",
        "champions_ask",
        [],
    ],
    [
        anyone | plyr,
        "champions_ask",
        [],
        "Where can I learn to fight?",
        "champions_ask_training",
        [],
    ],
    [
        anyone,
        "champions_ask_training",
        [],
        "When you travel around, you'll occasionally find a training ground in the\
 countryside. Many are run by old tournament champions, who are happy to teach everyone who comes by a few tricks.\
 I'm even considering to do that myself, when I get too old for the arena. And many towns also hold training matches\
 in between the tournaments. That's where I got most of my practice, back in the day. You can ask any local arena master about them.",
        "champions_ask",
        [],
    ],
    [
        anyone | plyr,
        "champions_ask",
        [],
        "Which tournaments are you planning to fight in?",
        "champions_ask_tournaments",
        [],
    ],
    [
        anyone,
        "champions_ask_tournaments",
        [],
        "{reg2?I think I'll pause for a while. There are no big events anytime soon.:{reg1?I haven't quite decided between the tournaments:I will be going to the tournament} at {s15}. Maybe we'll meet there.}",
        "champions_ask",
        [
            (assign, ":num_tournaments", 0),
            (try_for_range_backwards, ":town_no", towns_begin, towns_end),
              (party_slot_ge, ":town_no", slot_town_has_tournament, 1),
              (val_add, ":num_tournaments", 1),
              (try_begin),
                (eq, ":num_tournaments", 1),
                (str_store_party_name, s15, ":town_no"),
              (else_try),
                (str_store_party_name, s16, ":town_no"),
                (eq, ":num_tournaments", 2),
                (str_store_string, s15, "@{s16} and {s15}"),
              (else_try),
                (str_store_string, s15, "@{!}{s16}, {s15}"),
              (try_end),
            (try_end),
            (try_begin),
              (eq, ":num_tournaments", 0),
              (assign, reg2, 1),
            (else_try),
              (assign, reg2, 0),
              (store_sub, reg1, ":num_tournaments", 1),
            (try_end),
        ],
    ],
    [
        anyone | plyr,
        "champions_ask",
        [(troop_slot_eq, "$g_talk_troop", slot_troop_met_previously, 1)],
        "May I have your autograph?",
        "champions_ask_autograph",
        [],
    ],
    [
        anyone,
        "champions_ask_autograph",
        [],
        "Sure, here you go.",
        "champions_ask",
        [(troop_set_slot, "$g_talk_troop", slot_troop_met_previously, 2)],
    ],
    [
        anyone | plyr,
        "champions_ask",
        [
            (troop_slot_eq, "trp_fight_promoter", slot_troop_met_previously, 1),
            (eq, "$fistfight_opponent", 0),
        ],
        "I want to challenge you to a fistfight.",
        "champions_ask_challenge",
        [],
    ],
    [
        anyone,
        "champions_ask_challenge",
        [],
        "You mean with the guy who hosts the bets? Well, I need to stay fit, and I'm sure he'll like the publicity.\
 But I won't help him rigging the bets. I fight to win. Are you sure that you want to do this?",
        "champions_back_down",
        [],
    ],
    [anyone | plyr, "champions_ask", [], "That's all. Goodbye!", "close_window", []],
    [
        anyone | plyr,
        "champions_talk",
        [(troop_slot_ge, "$g_talk_troop", slot_troop_met_previously, 1)],
        "Just wanted to say hello.",
        "close_window",
        [],
    ],
    [
        anyone | plyr,
        "champions_back_down",
        [],
        "I am not afraid of you. I will fight.",
        "champions_challenge_accepted",
        [],
    ],
    [
        anyone,
        "champions_challenge_accepted",
        [],
        "Very well. Your fate awaits you in the cellar.",
        "close_window",
        [(assign, "$fistfight_opponent", "$g_talk_troop")],
    ],
    [
        anyone | plyr,
        "champions_back_down",
        [],
        "Actually, I'm having second thoughts.",
        "champions_challenge_retracted",
        [],
    ],
    [
        anyone,
        "champions_challenge_retracted",
        [],
        "Whatever. Would've been a boring fight anyway.",
        "close_window",
        [(assign, "$fistfight_opponent", 0)],
    ],
    [anyone, "merc_master_pretalk", [], "Anything else?", "merc_master_talk", []],
    [
        anyone | plyr,
        "merc_master_talk",
        [],
        "Yes, I might need some fighters.",
        "merc_master_trade",
        [],
    ],
    [
        anyone,
        "merc_master_trade",
        [],
        "Let me think who would be interested...",
        "merc_master_pretalk",
        [
            (set_mercenary_source_party, "$g_encountered_party"),
            (change_screen_buy_mercenaries),
        ],
    ],
    [
        anyone | plyr,
        "merc_master_talk",
        [],
        "Who are those people?",
        "merc_master_gossip",
        [],
    ],
    [
        trp.four_ways_bandit_chief,
        "merc_master_gossip",
        [],
        "They are the toughest bastards you can find west of Khudan.\
 They have to be, or they wouldn't have gotten old in the freebooting business. It's not a very forgiving line of work,\
 if you know what I mean. They may not be the most disciplined bunch, and a little hard to train, but they know\
 how to fight dirty, and they don't give a damn whose skulls they crack, unlike those so called 'professional soldiers'.",
        "merc_master_talk",
        [],
    ],
    [
        anyone,
        "merc_master_gossip",
        [],
        "Every one has their own story. Some are adventurous souls who would be bored by regular, steady jobs.\
 Some have fought the law and got away for now. Some have deserted from an army, but realized that fighting is still what they know best.\
 But what they all have in common is that they are veteran warriors who have proven their worth in many fights.",
        "merc_master_talk",
        [],
    ],
    [anyone | plyr, "merc_master_talk", [], "Thanks, that's all.", "close_window", []],
    [anyone, "constable_pretalk", [], "Anything else?", "constable_talk", []],
    [
        anyone | plyr,
        "constable_talk",
        [[store_num_regular_prisoners, reg(0)], [ge, reg(0), 1]],
        "I have some prisoners with me. Would you like a look?",
        "constable_bounty",
        [],
    ],
    [
        anyone,
        "constable_bounty",
        [],
        "Let me see what you have...",
        "constable_pretalk",
        [[change_screen_trade_prisoners]],
    ],
    [
        anyone | plyr,
        "constable_talk",
        [
            (store_num_regular_prisoners, reg0),
            (ge, reg0, 1),
            (store_sub, reg1, reg0, 1),
        ],
        "Would you take {reg1?these {reg0} prisoners:this prisoner}?",
        "constable_sell_all",
        [],
    ],
    [
        anyone,
        "constable_sell_all",
        [(call_script, "script_sell_all_prisoners", "p_main_party"), (gt, reg0, 0)],
        "Sure, here's your {reg0} denars.",
        "constable_pretalk",
        [(troop_add_gold, "trp_player", reg0)],
    ],
    [
        anyone,
        "constable_sell_all",
        [],
        "I'm sorry. I don't think I can collect a bounty or negotiate a ransom for {reg1?them:him}.",
        "constable_pretalk",
        [],
    ],
    [
        anyone | plyr,
        "constable_talk",
        [],
        "I'd better be going.",
        "constable_leave",
        [],
    ],
    [anyone, "constable_leave", [], "Stay out of trouble!", "close_window", []],
]

troops = [
    # Zendar
    [
        "tournament_master",
        "Tournament Master",
        "{!}Tournament Master",
        tf_hero,
        scn.zendar_center | entry(8),
        reserved,
        fac.commoners,
        [itm.nomad_armor, itm.falchion, itm.nomad_boots],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000088B0005113B5646C91B8E329C00000000001CB6D20000000000000000,
    ],
    [
        "constable_hareck",
        "Constable Hareck",
        "{!}Constable Hareck",
        tf_hero,
        scn.zendar_center | entry(11),
        reserved,
        fac.neutral,
        [itm.mail_with_surcoat, itm.mace_2, itm.leather_boots],
        def_attrib | level(5),
        wp(20),
        knows_common,
        0x0000000D7D00521348AD655B225AB51C00000000001DBA9D0000000000000000,
    ],
    [
        "mercenary_master",
        "Mercenary Master",
        "{!}Mercenary Master",
        tf_hero,
        scn.zendar_center | entry(13),
        reserved,
        fac.commoners,
        [itm.leather_jerkin, itm.sword_viking_1, itm.hide_boots],
        def_attrib | level(2),
        wp(20),
        knows_common,
        0x000000018200410627953194B256446500000000000D3CEB0000000000000000,
    ],
    [
        "zendar_armorer",
        "Armorer",
        "{!}Zendar Armorer",
        tf_hero | tf_female | tf_is_merchant,
        scn.zendar_center | entry(9),
        0,
        fac.commoners,
        [itm.aketon_green, itm.hide_boots],
        def_attrib | level(2),
        wp(20),
        knows_inventory_management_10,
        0x000000079F0010067ADC95CA5C663D1900000000001E28660000000000000000,
    ],
    [
        "zendar_weaponsmith",
        "Weaponsmith",
        "{!}Zendar Weaponsmith",
        tf_hero | tf_is_merchant,
        scn.zendar_center | entry(10),
        0,
        fac.commoners,
        [itm.leather_apron, itm.wrapping_boots],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        0x000000043D00501433A449A8EB9A5759000000000012A8740000000000000000,
    ],
    [
        "zendar_horse_merchant",
        "Horse Merchant",
        "{!}Zendar Horse Merchant",
        tf_hero | tf_is_merchant,
        scn.zendar_center | entry(12),
        0,
        fac.commoners,
        [itm.coarse_tunic, itm.straw_hat, itm.hide_boots],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        0x0000000FDD00761232E22A559DB64C1900000000001D28F40000000000000000,
    ],
    [
        "zendar_merchant",
        "Pawnbroker",
        "{!}Zendar Merchant",
        tf_hero | tf_is_merchant,
        scn.zendar_merchant | entry(9),
        0,
        fac.commoners,
        [itm.rich_outfit, itm.ankle_boots],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        0x0000000D7F0001521CCA5B326D48A74E00000000001E3AEE0000000000000000,
    ],
    [
        "zendar_bodger",
        "Bodger",
        "{!}Zendar Bodger",
        tf_hero | tf_is_merchant,
        scn.zendar_bodger | entry(9),
        0,
        fac.commoners,
        [itm.leather_apron, itm.ankle_boots],
        def_attrib | level(5),
        wp(20),
        knows_inventory_management_10,
        0x00000009BF005393575B67448B68B55400000000001DEA9C0000000000000000,
    ],
    [
        "zendar_tavernkeeper",
        "Tavern Keeper",
        "{!}Tavern Keeper",
        tf_hero | tf_randomize_face | tf_female,
        scn.the_happy_boar | entry(9),
        0,
        fac.commoners,
        [itm.peasant_dress, itm.hide_boots],
        def_attrib | level(2),
        wp(20),
        knows_common,
        woman_face_1,
        woman_face_2,
    ],
    [
        "fight_promoter",
        "Rough-Looking Guy",
        "Rough-Looking Guy",
        tf_hero | tf_randomize_face,
        scn.the_happy_boar | entry(10),
        0,
        fac.commoners,
        [itm.nomad_vest, itm.nomad_boots, itm.woolen_cap, itm.spiked_club],
        def_attrib | str_20 | agi_16 | level(20),
        wp(180),
        knows_common | knows_power_strike_5 | knows_ironflesh_3,
        bandit_face1,
        bandit_face2,
    ],
]

parties = [
  (
        "zendar",
        "Zendar",
        icon.castle_a | pf_location,
        no_menu,
        pt.none,
        fac.neutral,
        0,
        ai_bhvr_hold,
        0,
        (64, 9.3),
        [],
        300,
    ),
]
game_menus = [
    (
        "zendar",
        mnf_enable_hot_keys | mnf_scale_picture,
        "The free town of Zendar is widely known as a meeting point for mercenaries and bounty hunters. Constable Hareck is keeping the peace here,\
 but no banner is flown above the gates. Zendar is proud of keeping its neutrality and providing a safe haven to anyone in need of refuge.",
        "none",
        [
            (try_begin),
              (neq, "$fistfight_result", 0),
              (set_jump_mission, "mt_town_default"),
              (jump_to_scene, "scn_the_happy_boar", 16),
              (call_script, "script_enter_tavern", "p_zendar"),
            (try_end),
            (set_background_mesh, "mesh_pic_town1"),
        ],
        [
            (
                "zendar_enter",
                [],
                "Take a walk around the streets.",
                [
                    (assign, "$talk_context", 0),
                    (set_jump_mission, "mt_town_default"),
                    (jump_to_scene, "scn_zendar_center"),
                    (change_screen_mission),
                ],
                "Door to the town center.",
            ),
            (
                "zendar_tavern",
                [],
                "Visit the tavern.",
                [(call_script, "script_enter_tavern", "p_zendar")],
                "Door to the tavern.",
            ),
            (
                "zendar_merchant",
                [],
                "Speak with the pawnbroker.",
                [
                    (set_jump_mission, "mt_town_default"),
                    (jump_to_scene, "scn_zendar_merchant"),
                    (change_screen_mission),
                ],
                "Door to the pawn shop.",
            ),
            (
                "zendar_arena",
                [(eq, 1, 0)],
                "Enter the arena.",
                [
                    (set_jump_mission, "mt_town_default"),
                    (jump_to_scene, "scn_zendar_arena"),
                    (change_screen_mission),
                ],
                "Door to the arena.",
            ),
            (
                "zendar_bodger",
                [(eq, 1, 0)],
                "Speak with the polearm merchant.",
                [
                    (set_jump_mission, "mt_town_default"),
                    (jump_to_scene, "scn_zendar_bodger"),
                    (change_screen_mission),
                ],
                "Door to the polearm shop.",
            ),
            (
                "zendar_fight_club",
                [(eq, 1, 0)],
                "Enter the fight cellar.",
                [
                    (set_jump_mission, "mt_town_default"),
                    (jump_to_scene, "scn_fight_cellar"),
                    (change_screen_mission),
                ],
                "Door to the cellar.",
            ),
            (
                "zendar_wait",
                [
                    (assign, ":can_rest", 1),
                    (str_clear, s1),
                    (try_begin),
                      (party_get_num_companions, ":num_men", "p_main_party"),
                      (store_div, reg1, ":num_men", 4),
                      (val_add, reg1, 1),
                      (str_store_string, s1, "@ ({reg1} denars per night)"),
                      (store_troop_gold, ":gold", "trp_player"),
                      (lt, ":gold", reg1),
                      (assign, ":can_rest", 0),
                    (try_end),
                    (eq, ":can_rest", 1),
                ],
                "Wait here for some time{s1}.",
                [
                    (assign, "$auto_enter_town", "$g_encountered_party"),
                    (assign, "$g_town_visit_after_rest", 1),
                    (assign, "$g_last_rest_center", "$g_encountered_party"),
                    (assign, "$g_last_rest_payment_until", -1),
                    (
                        rest_for_hours_interactive,
                        24 * 7,
                        5,
                        0,
                    ),  # rest while not attackable
                    (change_screen_return),
                ],
            ),
            ("zendar_leave", [], "Leave.", [(leave_encounter), (change_screen_return)]),
        ],
    ),
]
scenes = [
    (
        "zendar_center",
        sf_generate,
        "none",
        "none",
        (0, 0),
        (100, 100),
        -100,
        "0x300bc5430001e0780000448a0000049f00007932",
        [],
        ["bonus_chest_0"],
        "outer_terrain_plain_1",
    ),
    (
        "the_happy_boar",
        sf_indoors,
        "interior_town_house_f",
        "bo_interior_town_house_f",
        (-100, -100),
        (100, 100),
        -100,
        "0",
        [],
        [],
    ),
    (
        "zendar_merchant",
        sf_indoors,
        "interior_town_house_i",
        "bo_interior_town_house_i",
        (-100, -100),
        (100, 100),
        -100,
        "0",
        [],
        [],
    ),
    (
        "zendar_arena",
        sf_generate,
        "none",
        "none",
        (0, 0),
        (100, 100),
        -100,
        "0xa0001d9300031ccb0000156f000048ba0000361c",
        [],
        [],
        "outer_terrain_plain",
    ),
    (
        "zendar_bodger",
        sf_indoors,
        "interior_town_house_j",
        "bo_interior_town_house_j",
        (-100, -100),
        (100, 100),
        -100,
        "0",
        [],
        [],
    ),
    (
        "fight_cellar",
        sf_indoors,
        "interior_town_house_aa",
        "bo_interior_town_house_aa",
        (-100, -100),
        (100, 100),
        -100,
        "0",
        [],
        [],
    ),
]

injection = {
    "zendar_bonus_chest": [
        [
            "bonus_chest_0",
            "{!}Zendar Chest",
            "{!}Bonus Chest",
            tf_hero | tf_inactive,
            0,
            reserved,
            fac.neutral,
            [
                itm.light_mail_and_plate,
                itm.mail_and_plate,
                itm.shield_kite_g,
                itm.shield_kite_h,
                itm.shield_kite_i,
                itm.shield_kite_k,
            ],
            def_attrib | level(18),
            wp(60),
            knows_common,
            0,
        ],
    ],
    "zendar_manhunters_spawn": [
        (else_try),
          (lt, ":manhunters", 6),
          (party_is_active, "p_zendar"),
          (call_script, "script_spawn_patrol", "pt_manhunters", "p_zendar", 45),
    ],
    "refresh_zendar": [
        (try_begin),
          (party_is_active, "p_zendar"),
          (
              call_script,
              "script_refresh_center_armorer",
              "p_zendar",
              "trp_zendar_armorer",
          ),
          (
              call_script,
              "script_refresh_center_weaponsmith",
              "p_zendar",
              "trp_zendar_weaponsmith",
          ),
          (
              call_script,
              "script_refresh_center_horse_merchant",
              "p_zendar",
              "trp_zendar_horse_merchant",
          ),
          (troop_sort_inventory, "trp_zendar_merchant"),
          (
              troop_ensure_inventory_space,
              "trp_zendar_merchant",
              60,
          ),  # holds on to the 10 most valuable items
          (store_troop_gold, ":cur_gold", "trp_zendar_merchant"),
          (try_begin),
            (lt, ":cur_gold", 10000),
            (store_random_in_range, ":new_gold", 1250, 2500),
            (call_script, "script_troop_add_gold", "trp_zendar_merchant", ":new_gold"),
          (try_end),
          (troop_clear_inventory, "trp_zendar_bodger"),
          (
              call_script,
              "script_add_matching_items_from_range",
              "trp_zendar_bodger",
              "itm_long_axe",
              "itm_wooden_shield",
              "script_cf_item_can_be_sold",
              num_merchandise_goods,
              100,
          ),
          (
              troop_ensure_inventory_space,
              "trp_zendar_bodger",
              merchant_inventory_space,
          ),
          (troop_sort_inventory, "trp_zendar_bodger"),
          (store_troop_gold, ":cur_gold", "trp_zendar_bodger"),
          (try_begin),
            (lt, ":cur_gold", 1000),
            (store_random_in_range, ":new_gold", 250, 500),
            (call_script, "script_troop_add_gold", "trp_zendar_bodger", ":new_gold"),
          (try_end),
        (try_end),
    ],
    "initialize_zendar_data": [
        (try_begin),
          (party_is_active, "p_zendar"),
          (party_set_slot, "p_zendar", slot_town_center, "scn_zendar_center"),
          (party_set_slot, "p_zendar", slot_town_tavern, "scn_the_happy_boar"),
          (party_set_slot, "p_zendar", slot_town_store, "scn_zendar_merchant"),
          (party_set_slot, "p_zendar", slot_town_arena, "scn_zendar_arena"),
          (party_set_slot, "p_zendar", slot_town_mayor, "trp_constable_hareck"),
          (party_set_slot, "p_zendar", slot_town_lord, "trp_constable_hareck"),
          (
              party_set_slot,
              "p_zendar",
              slot_town_tavernkeeper,
              "trp_zendar_tavernkeeper",
          ),
          (
              party_set_slot,
              "p_zendar",
              slot_town_weaponsmith,
              "trp_zendar_weaponsmith",
          ),
          (party_set_slot, "p_zendar", slot_town_armorer, "trp_zendar_armorer"),
          (
              party_set_slot,
              "p_zendar",
              slot_town_horse_merchant,
              "trp_zendar_horse_merchant",
          ),
          (party_set_slot, "p_zendar", slot_center_original_faction, "fac_kingdom_1"),
          (party_set_slot, "p_zendar", slot_town_prosperity, 75),
          (try_for_range, ":unused", 0, 5),
            (call_script, "script_rand", "trp_caravan_guard", mercenary_troops_end),
            (assign, ":troop", reg0),
            (call_script, "script_rand", 3, 7),
            (party_add_members, "p_zendar", ":troop", reg0),
          (try_end),
          (store_random_in_range, ":pawnbroker_gold", 10000, 12500),
          (
              call_script,
              "script_troop_add_gold",
              "trp_zendar_merchant",
              ":pawnbroker_gold",
          ),
        (try_end),
    ],
    "zendar_party_encounter": [
        (else_try),
          (eq, "$g_encountered_party", "p_zendar"),
          (jump_to_menu, "mnu_zendar"),
    ],
    "zendar_update_merceary_units": [
        (try_begin),
          (party_is_active, "p_zendar"),
          (call_script, "script_rand", mercenary_troops_begin, mercenary_troops_end),
          (party_set_slot, "p_zendar", slot_center_mercenary_troop_type, reg0),
          (call_script, "script_rand", 3, 8),
          (party_set_slot, "p_zendar", slot_center_mercenary_troop_amount, reg0),
          (
              party_set_slot,
              "p_zendar",
              slot_center_volunteer_troop_type,
              "trp_watchman",
          ),
          (call_script, "script_rand", 3, 8),
          (party_set_slot, "p_zendar", slot_center_volunteer_troop_amount, reg0),
          (try_begin),  # Try adding troops to merc selection
            (party_get_num_companions, ":num_mercs", "p_zendar"),
            (lt, ":num_mercs", 30),
            (call_script, "script_rand", "trp_caravan_guard", mercenary_troops_end),
            (assign, ":troop", reg0),
            (call_script, "script_rand", 3, 8),
            (party_add_members, "p_zendar", ":troop", reg0),
          (else_try),  # If full, remove a random stack instead
            (party_get_num_companion_stacks, ":n_stacks", "p_zendar"),
            (call_script, "script_rand", 0, ":n_stacks"),
            (party_stack_get_troop_id, ":stack_type", "p_zendar", reg0),
            (party_stack_get_size, ":stack_size", "p_zendar", reg0),
            (party_remove_members, "p_zendar", ":stack_type", ":stack_size"),
          (try_end),
        (try_end),
    ],
    "zendar_pawnbroker_stolen_loot": [
        (else_try),
          (party_is_active, "p_zendar"),
          (
              troop_sort_inventory,
              "trp_zendar_merchant",
          ),  # Looted items now go directly to the pawnbroker in Zendar
          (troop_ensure_inventory_space, "trp_zendar_merchant", 1),
          (troop_add_item, "trp_zendar_merchant", ":item_id", ":item_modifier"),
          (troop_sort_inventory, "trp_zendar_merchant"),
    ],
}
