from compiler import *

from module_troops import *

register_plugin(__name__)  # v0.0.1

factions = [
    (
        "peasant_rebels",
        "{!}Peasant Rebels",
        0,
        1.0,
        [("noble_refugees", -1.0)],
        [],
    ),
    ("noble_refugees", "{!}Noble Refugees", 0, 0.5, [], []),
]

troops = [
    [
        "peasant_rebel",
        "Peasant Rebel",
        "Peasant Rebels",
        tf_guarantee_armor,
        0,
        reserved,
        fac.peasant_rebels,
        [
            itm.cleaver,
            itm.knife,
            itm.pitch_fork,
            itm.sickle,
            itm.club,
            itm.stones,
            itm.leather_cap,
            itm.felt_hat,
            itm.felt_hat,
            itm.linen_tunic,
            itm.coarse_tunic,
            itm.nomad_boots,
            itm.wrapping_boots,
        ],
        def_attrib | level(4),
        wp(60),
        knows_common,
        vaegir_face_middle_1,
        vaegir_face_older_2,
    ],
    [
        "noble_refugee",
        "Noble Refugee",
        "Noble Refugees",
        tf_guarantee_boots | tf_guarantee_armor,
        0,
        0,
        fac.noble_refugees,
        [
            itm.sword_medieval_a,
            itm.leather_jacket,
            itm.hide_boots,
            itm.saddle_horse,
            itm.leather_jacket,
            itm.leather_cap,
        ],
        def_attrib | level(9),
        wp(100),
        knows_common,
        swadian_face_middle_1,
        swadian_face_old_2,
    ],
    [
        "noble_refugee_woman",
        "Noble Refugee Woman",
        "Noble Refugee Women",
        tf_female | tf_guarantee_armor | tf_guarantee_boots,
        0,
        0,
        fac.noble_refugees,
        [
            itm.knife,
            itm.dagger,
            itm.hunting_crossbow,
            itm.dress,
            itm.robe,
            itm.woolen_dress,
            itm.headcloth,
            itm.woolen_hood,
            itm.wrapping_boots,
        ],
        def_attrib | level(3),
        wp(45),
        knows_common,
        swadian_woman_face_1,
        swadian_woman_face_2,
    ],
]

party_templates = [
    (
        "peasant_rebels",
        "Peasant Rebels",
        icon.peasant,
        0,
        fac.peasant_rebels,
        bandit_personality,
        [(trp.peasant_rebel, 33, 97)],
    ),
    (
        "noble_refugees",
        "Noble Refugees",
        icon.gray_knight | carries_goods(12) | pf_quest_party,
        0,
        fac.noble_refugees,
        merchant_personality,
        [(trp.noble_refugee, 3, 5), (trp.noble_refugee_woman, 5, 7)],
    ),
]

dialogs = [
    [
        party_tpl | pt.peasant_rebels,
        "start",
        [],
        "TODO: What.",
        "peasant_rebel_talk",
        [],
    ],
    [anyone | plyr, "peasant_rebel_talk", [], "TODO: Die.", "close_window", []],
    [
        anyone | plyr,
        "peasant_rebel_talk",
        [],
        "TODO: Nothing.",
        "close_window",
        [(assign, "$g_leave_encounter", 1)],
    ],
    [
        party_tpl | pt.noble_refugees,
        "start",
        [],
        "TODO: What.",
        "noble_refugee_talk",
        [],
    ],
    [
        anyone | plyr,
        "noble_refugee_talk",
        [],
        "TODO: Nothing.",
        "close_window",
        [(assign, "$g_leave_encounter", 1)],
    ],
    [
        party_tpl | pt.refugees,
        "start",
        [],
        "We have been driven out of our homes because of this war.",
        "close_window",
        [(assign, "$g_leave_encounter", 1)],
    ],
    [
        trp.nobleman,
        "start",
        [],
        "Who are you? What do you want? Be warned, we are fully armed and more than capable to defend ourselves. Go to your way now or you will regret it.",
        "nobleman_talk_1",
        [(play_sound, "snd_encounter_nobleman")],
    ],
    [
        trp.nobleman | plyr,
        "nobleman_talk_1",
        [],
        "I demand that you surrender to me.",
        "nobleman_talk_2",
        [],
    ],
    [
        trp.nobleman | plyr,
        "nobleman_talk_1",
        [],
        "I am sorry sir. You may go.",
        "close_window",
        [(assign, "$g_leave_encounter", 1)],
    ],
    [
        trp.nobleman,
        "nobleman_talk_2",
        [],
        "Surrender to a puny peasant like you? Hah. Not likely.",
        "close_window",
        [[encounter_attack]],
    ],
    [
        trp.nobleman,
        "enemy_defeated",
        [],
        "Parley! I am of noble birth, and I ask for my right to surrender.",
        "nobleman_defeated_1",
        [],
    ],
    [
        trp.nobleman | plyr,
        "nobleman_defeated_1",
        [],
        "And I will grant you that. If you can be ransomed of course...",
        "nobleman_defeated_2",
        [],
    ],
    [
        trp.nobleman,
        "nobleman_defeated_2",
        [],
        "Oh, you need not worry about that. My family would pay a large ransom for me.",
        "nobleman_defeated_3",
        [],
    ],
    [
        trp.nobleman | plyr,
        "nobleman_defeated_3",
        [[str_store_troop_name, 1, "$nobleman_quest_giver"]],
        "Hmm. {s1} will be happy about this... Then you are my prisoner.",
        "close_window",
        [
            [assign, "$nobleman_quest_succeeded", 1],
            [assign, "$nobleman_quest_nobleman_active", 0],
        ],
    ],
]
